### ISSUE TITLE
Include version info

### ISSUE THREAD

**Issue by jobec** [bvantagelimited/freeradius_exporter#1]
It would be great to have a version in this package, that can be printed with a `-version` flag.

This allows to compare versions and automatically upgrade the binary.

See https://github.com/oliver006/redis_exporter/blob/7eb3772cedb28d8c4c0299a8167aa22272be0338/main.go#L53

**Comment by gen2brain** [comment]
Version information is added in https://github.com/bvantagelimited/freeradius_exporter/commit/9241c162f19b55cd4114023f69f82b73e89006fb , the release is done with `goreleaser` which passes `ldflags` by default:

```
$ ./freeradius_exporter -version
freeradius_exporter 0.1.0 e55eb6d1bffd0522926241adb86adba5389908cf 2019-06-06T11:42:33Z
```

**Comment by jobec** [comment]
That is... fast! 😮 

Thanks, it makes deploying a lot easier for us.

**Comment by jobec** [comment]
You may also want to add this exporter to these 2 lists:

- https://prometheus.io/docs/instrumenting/exporters/
- https://github.com/prometheus/prometheus/wiki/Default-port-allocations

**Comment by gen2brain** [comment]
Yes, that will require to change the default port, and there were some complaints about having `radius.secret` option, but as you noticed it allows to have everything just works without too many configuring.
Simple config file will be also nice to have, but I first wanted to merge the exporter we have for version 4.0.x (not yet released) that use `radmin` tool and not `status-server`.

**Comment by jobec** [comment]
Port `9812` doesn't seem to be taken already.
Nice hint to the default RADIUS port btw ;)
