### ISSUE TITLE
External config file

### ISSUE THREAD

**Issue by TcaManager** [bvantagelimited/freeradius_exporter#10]
Hi,
Is there a way to add an external default config file, like /etc/default/freeradius_exporter for example?
Thanks.

**Comment by gen2brain** [comment]
There should be support for config file first, it is not supported currently so when it is added it can probably have some default location. And /etc/default is a bad example, it is distro-specific and only exists on some distros.;

**Comment by gen2brain** [comment]
Ok, need to check and test, API was different.

**Comment by gen2brain** [comment]
Support for config file added in https://github.com/bvantagelimited/freeradius_exporter/commit/b32426733d6d536ad5e14811cbd5a318096540dd.
