### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DarkWingDuck65** [bvantagelimited/freeradius_exporter#11]
Hi, hope you can help. Not familiar with go, trying to install it on the freeradius server, but when I run:

_go get -u github.com/bvantagelimited/freeradius_exporter_

I get the following error:

_# github.com/prometheus/procfs
go/src/github.com/prometheus/procfs/proc_snmp6.go:147:6: undefined: errors.Is_

Anything I'm missing?

**Comment by gen2brain** [comment]
You are trying to use the now deprecated method to install (I will change that in README). Use `go install github.com/bvantagelimited/freeradius_exporter@latest`.

**Comment by gen2brain** [comment]
Changed in https://github.com/bvantagelimited/freeradius_exporter/commit/79d7ee79edce4214a8c6b4b221ff6bffb8b905ef.

**Comment by DarkWingDuck65** [comment]
Thanks, but it cannot. find the package now

_go install github.com/bvantagelimited/freeradius_exporter@latest
can't load package: package github.com/bvantagelimited/freeradius_exporter@latest: cannot find package "github.com/bvantagelimited/freeradius_exporter@latest" in any of:
        /usr/lib/go-1.10/src/github.com/bvantagelimited/freeradius_exporter@latest (from $GOROOT)
        /root/go/src/github.com/bvantagelimited/freeradius_exporter@latest (from $GOPATH)_

**Comment by gen2brain** [comment]
Ah, you are using a very old Go version. It works here, Go modules are introduced in ver 1.11 I think. The current version is 1.18, you need a new version in order to install it. There is also compiled binary file in releases you can use.

```
$ go install github.com/bvantagelimited/freeradius_exporter@latest
go: downloading github.com/bvantagelimited/freeradius_exporter v0.0.0-20220420074442-79d7ee79edce

$ freeradius_exporter
2022/04/20 10:47:20 Providing metrics at :9812/metrics
```

**Comment by DarkWingDuck65** [comment]
Kewl, running 

_go version go1.10.4 linux/amd64_

Will install from source and test, fanks!

**Comment by DarkWingDuck65** [comment]
Confirming installing go version 1.18 worked. Fanks!
