### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by DarkWingDuck65** [bvantagelimited/freeradius_exporter#12]
In reference to issue number 11

Thanks, but it cannot. find the package now

go install github.com/bvantagelimited/freeradius_exporter@latest
can't load package: package github.com/bvantagelimited/freeradius_exporter@latest: cannot find package "github.com/bvantagelimited/freeradius_exporter@latest" in any of:
/usr/lib/go-1.10/src/github.com/bvantagelimited/freeradius_exporter@latest (from $GOROOT)
/root/go/src/github.com/bvantagelimited/freeradius_exporter@latest (from $GOPATH)

**Comment by gen2brain** [comment]
https://github.com/bvantagelimited/freeradius_exporter/issues/11#issuecomment-1103644301
