### ISSUE TITLE
Document exported metrics 

### ISSUE THREAD

**Issue by varac** [bvantagelimited/freeradius_exporter#14]
I'd like to know what metrics are exported before I set the exporter up, please document an example output in the README.md.
Thanks !

**Comment by varac** [comment]
Also, I see that [enabling the status server](https://github.com/bvantagelimited/freeradius_exporter/issues/7#issuecomment-580256595) is a requirement, it would be good to document this as well.

**Comment by samkhune** [comment]
hi sir,
when i run ./freeradius_exporter i got following error.
2022/07/29 05:51:25 exchange failed: read udp 127.0.0.1:49140->127.0.0.1:18121: read: connection refused.

and also tell me that how to install from source code.
