### ISSUE TITLE
Use a hostname for RADIUS_ADDRESS

### ISSUE THREAD

**Issue by kkalev** [bvantagelimited/freeradius_exporter#15]
Thank you for freeradius_exporter

We are using the exporter in a docker compose context with FreeRADIUS, MariaDB and freeradius_exporter. The fact that freeradius_exporter only accepts an IP address for the RADIUS server is a drawback since it necessitates adding specific (private) IP addresses for the FreeRADIUS server and freeradius_exporter containers.

It would be very helpful if freeradius_exporter also accepted hostnames since Docker will automagically assign the service name to an IP address. That way we can use RADIUS_ADDRESS=radius:1812 instead of RADIUS_ADDRESS=10.5.0.5:1812

**Comment by gen2brain** [comment]
@kkalev https://github.com/bvantagelimited/freeradius_exporter/commit/90d0a9c55664d52f5c6837823d77fb2b24f5e591 should address this, can you test it?

**Comment by kkalev** [comment]
Works great!!

Thanks a lot

**Comment by gen2brain** [comment]
A new release is uploaded.
