### ISSUE TITLE
radius.homeserver

### ISSUE THREAD

**Issue by sascha-wi** [bvantagelimited/freeradius_exporter#17]
Hello,
I am getting an error in the syslog for the exporter: 
`Failed to find home server IP`

Can you give me a hint on how the config has to look like when the freeradius and freeradius_exporter are running on the same server? I am not 100% what homeserver refers to in this case.

**Comment by gen2brain** [comment]
There is an example config file in this repo, not sure what else you would need, you configure IP:port, and secret. This is not the best place to get an answer to what is homeserver, if you don't use it don't configure it, it is optional. Check FreeRADIUS documentation if you want to learn more about homeservers.

**Comment by sascha-wi** [comment]
Just fyi, the exporter is working, but I still get this error messages. 
`Jun 14 14:29:44 ingalls freeradius_exporter[2532481]: 2023/06/14 14:29:44 error form stats server (main _localhost_:18121 or home server: _radsecproxy_:1812): '
Home server is not auth'`
even when I remove the radsecproxy, which according to the documentation I used to set up the freeradius server is a home server.

**Comment by gen2brain** [comment]
That is related to FR configuration, stats server, etc. Not sure what do you think exporter should do when FR is not configured properly, that is out of scope for this project.
