### ISSUE TITLE
Don't see any data

### ISSUE THREAD

**Issue by gk-fschubert** [bvantagelimited/freeradius_exporter#7]
Hey, sorry and maby is my configuration wrong. All metrics the exporter displays is 0 except 'freeradius_up'. Im authenticating with eap-tls. The following accounting types are activated: detail, unix, exec. And i can see the statistic type with what the accounting server is answering is "All". 

It would be very nice if you can help me.

**Comment by gen2brain** [comment]
Do you have the status server configured, and can query with radclient like in example here https://wiki.freeradius.org/config/Status#querying-with-radclient ?

**Comment by gk-fschubert** [comment]
You made my day! Haven't setup the status server. Thank you
